### ISSUE TITLE
Shutdown SDK

### ISSUE THREAD

**Issue by lukasz-szyszkowski** [Synerise/synerise-ios-sdk#2]
Hey,

is there any possibility of shutdown/dispose/deinitialize SDK? I need to shut down SDK in case of user analytic consent denied.

**Comment by awoczek** [comment]
Maybe it is approach for your case - https://hub.synerise.com/developers/mobile-sdk/settings/#enabledisable-sdk?

**Comment by awoczek** [comment]
@lukasz-szyszkowski 

Check available settings for shutdown modules or whole SDK processing - https://hub.synerise.com/developers/mobile-sdk/settings

I am closing the issue for now.
