### ISSUE TITLE
Unable to read the license file

### ISSUE THREAD

**Issue by mnowackifm** [Synerise/synerise-ios-sdk#9]
The issue has been introduced in the release 4.18.1. It produces warnings in the console after installing SyneriseSDK via CocoaPods.

[!] Unable to read the license file `https://github.com/Synerise/synerise-ios-sdk/blob/master/LICENSE` for the spec `SyneriseSDK (4.19.0)`

**Comment by awoczek** [comment]
We are investigating the problem, thank you for your response.

**Comment by awoczek** [comment]
It is fixed in 4.19.1 SDK version
